/*
 * generated by Xtext
 */
package edu.upb.lp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ListaUiModule extends edu.upb.lp.ui.AbstractListaUiModule {
	public ListaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
