/*
 * generated by Xtext
 */
package edu.upb.lp.ui.contentassist

import edu.upb.lp.ui.contentassist.AbstractListaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ListaProposalProvider extends AbstractListaProposalProvider {
}
