/*
 * generated by Xtext
 */
package edu.upb.lp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.upb.lp.ui.internal.ListaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ListaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ListaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ListaActivator.getInstance().getInjector(ListaActivator.EDU_UPB_LP_LISTA);
	}
	
}
