/*
* generated by Xtext
*/
package edu.upb.lp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ListaStandaloneSetup extends ListaStandaloneSetupGenerated{

	public static void doSetup() {
		new ListaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

